# Generated by Django 5.0.4 on 2024-06-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pizza_type',
            field=models.CharField(default='qwerty', max_length=100),
            preserve_default=False,
        ),
    ]
